version: '3.9'
services:
  mongodb:
    image: mongo:4.0.28
    container_name: mongodb-node-api
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./bind-mount/mongodb:/data/db
  api:
    build: .
    container_name: node-api
    restart: always
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - MONGODB_URL=mongodb://mongodb/node-api
    volumes:
      - ./bind-mount/logs:/usr/src/app/bind-mount/logs
    depends_on:
      - mongodb
